spring.application.name=Bai2

logging.level.root=WARN

logging.level.com.example.demo.controller=INFO
logging.level.com.example.demo.service=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} - %5p - %logger{36} - %msg%n