spring.application.name=Bai1

#Config Logging - C?p ?? log : trace -> debug -> info -> warn -> error
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd hh:mm:ss.SSS} - %-5level - %logger{50} - %msg%n 
logging.logback.rollingpolicy.max-file-size=20MB
logging.logback.rollingpolicy.max-history=30
logging.level.root=INFO
logging.level.ra.demo = INFO